steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  # Set the preferred application environment for the current project
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'env', '--', '$PROJECT_ID']
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo $PROJECT_ID | rev | cut -d- -f1 | rev > .appenv
  # Run unit tests
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test:unit']
  # Run integration tests (in customized Docker image with Java 8 installed)
  - name: 'gcr.io/$PROJECT_ID/npm'
    args: ['run', 'test:integration']
  # Build and deploy to Firebase
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'deploy']
