steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  # Set preferred application environment
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'env:dev2']
  # Run unit tests
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test:unit']
  # Run integration tests (in customized Docker image with Java 8 installed)
  - name: 'gcr.io/$PROJECT_ID/npm'
    args: ['run', 'test:integration']
  # Build and deploy to Firebase
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'deploy']
